blank_issues_enabled: false
contact_links:
    - name: Vencord Support Server
      url: https://discord.gg/D9uwnFnqmd
      about: "Need Help? Join our support server and ask in the #vcord-support channel!"
