/*
 * VCord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "__patches__"; // auto generated by the build script
import "./appBadge";
import "./arrpc";
import "./fixes";
import "./ipcCommands";
import "./themedSplash";

export * as Components from "./components";
export { Settings };

import SettingsUi from "./components/settings/Settings";
import { VCordLogger } from "./logger";
import { Settings } from "./settings";

import type SettingsPlugin from "@vencord/types/plugins/_core/settings";

VCordLogger.log("read if cute :3");
VCordLogger.log("VCord v" + VCordNative.app.getVersion());

const customSettingsSections = (Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin).customSections;

customSettingsSections.push(() => ({
    section: "VCord",
    label: "VCord Settings",
    element: SettingsUi,
    className: "vc-vcord-settings"
}));
